# Makefile for main.c and mat_multiply.c

CC = gcc
CFLAGS = -g -Wall -Werror

# List of object files to be generated
OBJ = mat_multiply.o

# Main target
mat_multiply.out: $(OBJ)
	$(CC) $(CFLAGS) -o mat_multiply.out $^

# Rule to build object files
%.o: %.c %.h
	$(CC) $(CFLAGS) -c $<

# Clean rule
clean:
	rm -fr *.o *.out
